stages:
- name: compile
  steps:
  - runScriptConfig:
      image: maven:3-jdk-8
      shellScript: mvn clean package
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: 10.3.10.131:5000/cloud-scheduler:v1
      pushRemote: true
      registry: 10.3.10.131:5000
    env:
      PLUGIN_INSECURE: "true"
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
