apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-scheduler-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-scheduler
  template:
    metadata:
      labels:
        app: cloud-scheduler
        track: stable
    spec:
      containers:
        - name: cloud-scheduler
          image: 10.3.10.131:5000/cloud-scheduler:v${CICD_EXECUTION_SEQUENCE}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: cloud-scheduler-svc
spec:
  type: NodePort
  selector:
    app: cloud-scheduler
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080